 DROP SCHEMA IF EXISTS AlertAcademy;

CREATE SCHEMA AlertAcademy;

use AlertAcademy;

CREATE TABLE Person (
Person_ID INT(5) ZEROFILL NOT NULL AUTO_INCREMENT UNIQUE,
First_Name VARCHAR(30) NOT NULL,
Last_Name VARCHAR(30) NOT NULL,
Email VARCHAR(65) NOT NULL,
Password VARCHAR(30) NOT NULL,
 UsrNm VARCHAR(30) NOT NULL UNIQUE,

CONSTRAINT Person_pk PRIMARY KEY (Person_ID)) engine=innodb;

INSERT INTO Person VALUES(NULL, '', '', '', 'password', 'admin');

/* check minimum length of password on front-end */

CREATE TABLE Cls (
ClsID INT(5) ZEROFILL NOT NULL AUTO_INCREMENT UNIQUE,
ClsName VARCHAR(30) NOT NULL,
Color int DEFAULT 0,
ProfName VARCHAR(30),
School VARCHAR(45) DEFAULT 'N/A',
Person_ID INT(5) ZEROFILL DEFAULT 0,

CONSTRAINT Cls_PK PRIMARY KEY (ClsID),
CONSTRAINT Cls_FK FOREIGN KEY (Person_ID) REFERENCES Person(Person_ID)) engine=innodb;

DELIMITER //

CREATE TRIGGER In_Person AFTER INSERT ON Person
FOR EACH ROW
BEGIN

INSERT INTO Cls VALUES (NULL, 'N/A', 0, NULL, NULL, NEW.Person_ID);

END //

DELIMITER ;

CREATE TABLE Assign (
Assign_ID INT(5) ZEROFILL NOT NULL AUTO_INCREMENT UNIQUE,
Assign_Name VARCHAR(30) NOT NULL,
Due DATE NOT NULL,
Descrip VARCHAR(100),
Person_ID INT(5) ZEROFILL DEFAULT 0,
ClsID INT(5) ZEROFILL DEFAULT 0,

CONSTRAINT Assign_PK PRIMARY KEY (Assign_ID),
CONSTRAINT Assign_FK1 FOREIGN KEY(Person_ID) REFERENCES Person(Person_ID),
CONSTRAINT Assign_FK2 FOREIGN KEY(ClsID) REFERENCES Cls(ClsID)) engine=innodb;

DELIMITER //

CREATE PROCEDURE Clear_Cls
(IN CID INT(5))
READS SQL DATA
BEGIN 
 
DELETE FROM Assign WHERE (Assign.ClsID = CID);
DELETE FROM Cls WHERE (Cls.ClsID = CID);

END //

CREATE PROCEDURE Clear_Person
(IN PID INT(5))
READS SQL DATA
BEGIN 

DELETE FROM Assign WHERE (Assign.Person_ID = PID);
DELETE FROM Cls WHERE (Cls.Person_ID = PID);
DELETE FROM Person WHERE (Person.Person_ID = PID);

END //

DELIMITER ;
